### ISSUE TITLE
Cannot rotate the map

### ISSUE THREAD

**Issue by beekill95** [mapfit/aptfit-android-sample#1] opened 2018-08-05 13:48 UTC
I build and run the app successfully on my Samsung Galaxy Note 4. However, whenever I try to rotate the map using two fingers, the app crashes.

This is the stack trace when the app crashes:
```
2123-2206/com.mapfit.realestate E/AndroidRuntime: FATAL EXCEPTION: ForkJoinPool.commonPool-worker-1
                                                                     Process: com.mapfit.realestate, PID: 2123
                                                                     android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                                                                         at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8181)
                                                                         at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1307)
                                                                         at android.view.ViewGroup.invalidateChild(ViewGroup.java:5428)
                                                                         at android.view.View.invalidateInternal(View.java:13932)
                                                                         at android.view.View.invalidate(View.java:13896)
                                                                         at android.view.View.invalidate(View.java:13880)
                                                                         at android.widget.ImageView.setImageMatrix(ImageView.java:779)
                                                                         at com.mapfit.android.MapView$rotateCompassButton$1.doResume(MapView.kt:494)
                                                                         at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
                                                                         at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
                                                                         at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
                                                                         at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1388)
                                                                         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:251)
                                                                         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:845)
                                                                         at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1674)
                                                                         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1629)
                                                                         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by dgngulcan** [comment] 2018-08-07 19:05
Hi, the issue is fixed on Mapfit SDK version `2.1.1` and I've updated the project(e1ed989).

**Closed as completed by dgngulcan** 2018-08-07 19:05 UTC
Labels: bug
